### ISSUE TITLE
pull image failed~!!!

### ISSUE THREAD

**Issue by MainPoser** [lank8s/lank8s.github.io#1]
# gcr.io/authenticated-image-pulling/alpine:3.7
$ docker pull gcr.lank8s.cn/authenticated-image-pulling/alpine:3.7
Error response from daemon: error parsing HTTP 403 response body: unexpected end of JSON input: ""

# k8s.gcr.io/conformance:v1.24.0
$ docker pull lank8s.cn/conformance:v1.24.0
Error response from daemon: error parsing HTTP 403 response body: unexpected end of JSON input: ""

**Comment by liangyuanpeng** [comment]
测试了一下， gcr.io/authenticated-image-pulling/alpine:3.7 应该是私有镜像？ 需要登陆，目前 lank8scn 只支持公开的镜像

`k8s.gcr.io/conformance:v1.24.0` 这个测试了可以拉取.

```
lan@lan:~/repo/vms$ docker pull lank8s.cn/conformance:v1.24.0
v1.24.0: Pulling from conformance
36698cfa5275: Already exists 
6a8659ec8836: Pull complete 
fd9cb207c78f: Pull complete 
1836f0836070: Pull complete 
80e04d41a01d: Pull complete 
bbabd0b4cb52: Pull complete 
ca1b458bdb23: Pull complete 
28b1a954b9f5: Pull complete 
05e5739bcaea: Pull complete 
1d239ed0af7f: Pull complete 
Digest: sha256:b9f91081bf4b080ad3b29977b15594ba68f0380242e35f31850616c12cedd323
Status: Downloaded newer image for lank8s.cn/conformance:v1.24.0
lank8s.cn/conformance:v1.24.0
```

**Comment by MainPoser** [comment]
thank you!

**Comment by MainPoser** [comment]
!!!
